export * from './player'
export * from './points'
export * from './obstacles'
export * from './background'
export * from './game-over'
export * from './game-start'
export * from './logo'
export * from './score-elem'
